apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: pankajkm884/testweb1:latest
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                 configMapKeyRef:
                   name: db-data
                   key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-data
                  key: DATABASE_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-data
                  key: DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8085
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-data
data:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: Chetu@123
  DATABASE_URL: jdbc:mysql://localhost:3306/test

